# Generated by Django 2.2.10 on 2021-11-24 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20211123_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='delivered_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='pending_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='received_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='registered_date',
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('Registered', 'Registered'), ('Delivered', 'Delivered'), ('Received', 'Received'), ('Pending', 'Pending'), ('Accepted', 'Accepted')], max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='app.Transaction')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
