# Generated by Django 2.2.10 on 2021-11-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211124_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='accepted_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pending_date',
            field=models.DateField(null=True),
        ),
    ]
