# Generated by Django 2.2.10 on 2021-11-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211124_1544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Baru',
        ),
    ]
