# Generated by Django 2.2.10 on 2021-11-25 17:29

import app.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_baru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=app.models.company_location)),
                ('address', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
